let arrPokemons = [
     {   name: "Пикачу",
         photo: "https://pokemongolife.ru/p/Pikachu.png",
         hp: 99,
         hunger: 100,
         hygiene: 100,
         depression: 100,
     },
     {
         name: "Иви",
         photo: "https://pokemongolife.ru/p/Eevee.png",
         hp: 99,
         hunger: 100,
         hygiene: 100,
         depression: 100,
     },
     {
        name: "Бульбазавр",
        photo: "https://pokemongolife.ru/p/Bulbasaur.png",
        hp: 99,
        hunger: 100,
        hygiene: 100,
        depression: 100,
    },
    {
        name: "Амбреон",
        photo: "https://pokemongolife.ru/p/Umbreon.png",
        hp: 99,
        hunger: 100,
        hygiene: 100,
        depression: 100,
    },
    {
        name: "Мьюту",
        photo: "https://pokemongolife.ru/p/Mewtwo.png",
        hp: 99,
        hunger: 100,
        hygiene: 100,
        depression: 100,
    },
    {
        name: "Чаризард",
        photo: "https://pokemongolife.ru/p/Charizard.png",
        hp: 99,
        hunger: 100,
        hygiene: 100,
        depression: 100,
    },
    {
        name: "Сквиртл",
        photo: "https://pokemongolife.ru/p/Squirtle.png",
        hp: 99,
        hunger: 100,
        hygiene: 100,
        depression: 100,
    },
    {
        name: "Чармандер",
        photo: "https://pokemongolife.ru/p/Charmander.png",
        hp: 99,
        hunger: 100,
        hygiene: 100,
        depression: 100,
    },
    {
        name: "Лифеон",
        photo: "https://pokemongolife.ru/p/Leafeon.png",
        hp: 99,
        hunger: 100,
        hygiene: 100,
        depression: 100,
    },
    {
        name: "Псидак",
        photo: "https://pokemongolife.ru/p/Psyduck.png",
        hp: 99,
        hunger: 100,
        hygiene: 100,
        depression: 100,
    },
    {
        name: "Гласеон",
        photo: "https://pokemongolife.ru/p/Glaceon.png",
        hp: 99,
        hunger: 100,
        hygiene: 100,
        depression: 100,
    }
]